# Generated by Django 4.2.4 on 2023-08-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("train", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="train",
            name="seats_num",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("trip", "seat")},
        ),
    ]
