# Generated by Django 4.2.4 on 2023-08-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("train", "0002_train_seats_num_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="train",
            old_name="cargo_num",
            new_name="luggage_space",
        ),
        migrations.RemoveField(
            model_name="train",
            name="places_in_cargo",
        ),
        migrations.AddField(
            model_name="trip",
            name="train_staff",
            field=models.ManyToManyField(
                related_name="trips",
                to="train.crew"
            ),
        ),
    ]
