# Generated by Django 4.2.4 on 2023-08-17 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("train", "0003_rename_cargo_num_train_luggage_space_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="train.order",
            ),
        ),
    ]
