# Generated by Django 4.2.4 on 2023-08-21 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("train", "0005_rename_cargo_ticket_luggage_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="train",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crew",
                to="train.train",
            ),
            preserve_default=False,
        ),
    ]
