# Generated by Django 4.2.4 on 2023-08-21 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("train", "0006_crew_train"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crew",
            name="train",
        ),
        migrations.RemoveField(
            model_name="trip",
            name="train_staff",
        ),
        migrations.AddField(
            model_name="crew",
            name="assigned_trips",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trips",
                to="train.trip",
            ),
        ),
    ]
